import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/contexts/theme-provider";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children:ReactNode}) {
  return (
    <>
      <html lang="pt-BR" suppressHydrationWarning>
        <head />
        <body
        className={cn(
          "text-foreground flex  flex-col lg:flex-row font-sans antialiased  bg-background relative",
          
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
